// Code generated by go2go; DO NOT EDIT.


//line m/map_01.go2:1
package m

//line m/map_01.go2:1
import (
//line m/map_01.go2:1
 "errors"
//line m/map_01.go2:1
 "github.com/pvillela/go-light-collections/pkg/g2lc/pair"
//line m/map_01.go2:1
)

//line m/map_01.go2:1
type Importable୦ int

//line m/map_01.go2:1
var _ = errors.As

//line m/map_01.go2:1
type _ pair.Importable୦
