// Code generated by go2go; DO NOT EDIT.


//line slice/slice_0.go2:1
package slice

//line slice/slice_0.go2:1
import (
//line slice/slice_0.go2:1
 "errors"
//line slice/slice_0.go2:1
 "github.com/pvillela/go-light-collections/pkg/g2lc/pair"
//line slice/slice_0.go2:1
 "reflect"
//line slice/slice_0.go2:1
 "sort"
//line slice/slice_0.go2:1
)

//line slice/slice_0.go2:1
type Importable୦ int

//line slice/slice_0.go2:1
var _ = errors.As

//line slice/slice_0.go2:1
type _ pair.Importable୦

//line slice/slice_0.go2:1
var _ = reflect.Append

//line slice/slice_0.go2:1
type _ sort.Float64Slice
