// Code generated by go2go; DO NOT EDIT.


//line aliases.go2:1
package g2lc

//line aliases.go2:1
import (
//line aliases.go2:1
 "errors"
//line aliases.go2:1
 "github.com/pvillela/go-light-collections/pkg/g2lc/m"
//line aliases.go2:1
 "github.com/pvillela/go-light-collections/pkg/g2lc/pair"
//line aliases.go2:1
 "github.com/pvillela/go-light-collections/pkg/g2lc/set"
//line aliases.go2:1
 "github.com/pvillela/go-light-collections/pkg/g2lc/slice"
//line aliases.go2:1
 "github.com/pvillela/go-light-collections/pkg/util/util"
//line aliases.go2:1
 "reflect"
//line aliases.go2:1
 "sort"
//line aliases.go2:1
)

//line aliases.go2:1
type Importable୦ int

//line aliases.go2:1
var _ = errors.As

//line aliases.go2:1
type _ m.Importable୦
//line aliases.go2:1
type _ pair.Importable୦
//line aliases.go2:1
type _ set.Importable୦
//line aliases.go2:1
type _ slice.Importable୦

//line aliases.go2:1
var _ = util.MaxInt
//line aliases.go2:1
var _ = reflect.Append

//line aliases.go2:1
type _ sort.Float64Slice
