// Code generated by go2go; DO NOT EDIT.


//line set/set_0.go2:1
package set

//line set/set_0.go2:1
import (
//line set/set_0.go2:1
 "errors"
//line set/set_0.go2:1
 "github.com/pvillela/go-light-collections/pkg/g2lc/m"
//line set/set_0.go2:1
 "github.com/pvillela/go-light-collections/pkg/g2lc/pair"
//line set/set_0.go2:1
 "github.com/pvillela/go-light-collections/pkg/util/util"
//line set/set_0.go2:1
)

//line set/set_0.go2:1
type Importable୦ int

//line set/set_0.go2:1
var _ = errors.As

//line set/set_0.go2:1
type _ m.Importable୦
//line set/set_0.go2:1
type _ pair.Importable୦

//line set/set_0.go2:1
var _ = util.MaxInt
